CI: Update tested pytest to fix build with Python 3.14
We got:

    DEBUG:   File "/builddir/build/BUILD/python-pytest-7.2.0-build/BUILDROOT/usr/lib/python3.14/site-packages/_pytest/assertion/rewrite.py", line 670, in run
    DEBUG:     and isinstance(item.value, ast.Str)
    DEBUG:                                ^^^^^^^
    DEBUG: AttributeError: module 'ast' has no attribute 'Str'

Version 8.0.2 builds in Fedora 43, 42, 41, EPEL 10 (still without tests).

The setup.py manipulation was moved to pluggy,
as pytest 8 no longer has setup.py.